# 이름 설정
name: Node.js CI/CD

# 어떤 트리거로 작동할 것인 지
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version : [19.x, 20.x, 22.x]

    steps:
      - name: 체크아웃 레포지토리
        uses: actions/checkout@v2

      - name: Node 설정
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: 의존성 설치
        run: npm install

      - name: 테스트 실행
        run: npm test

  build-and-push-images:
    needs:
      - test
    runs-on: ubuntu-latest
    if : github.ref == 'refs/heads/main'

    steps:
      - name: 체크아웃 레포지토리
        uses: actions/checkout@v2

      - name: 도커허브 로그인
        uses: docker/login-action@v2
        with:
          username : ${{secrets.DOCKER_USERNAME}}
          password : ${{secrets.DOCKER_TOKEN}}

      - name: 빌드 및 이미지 푸시
        run: |
          docker build --platform linux/amd64 -t ${{secrets.DOCKER_USERNAME}}/express-hello-world:latest .
          docker push ${{secrets.DOCKER_USERNAME}}/express-hello-world:latest

  deploy :
    needs: build-and-push-images
    runs-on: ubuntu-latest

    steps:
      - name: SSH키 준비
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SERVER_HOST}} > ~/.ssh/known_hosts
      - name: 도커 설치 여부
        id : check-docker
        run: |
          DOCKER_EXISTS=$(ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SEVER_HOST}} 'command -v docker >/dev/null && echo "true" || echo "false"')
          echo "docker_exists=$DOCKER_EXISTS" >> $GITHUB_OUTPUT

      - name: 노드 설치 여부
        id : check-nodejs
        run: |
          NODE_EXISTS=$(ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} 'command -v node >/dev/null $$ echo "true" || echo "false"')
          echo "node_exists=$NODE_EXISTS" >> $GITHUB_OUTPUT

      - name: EC2 도커 설치하기 (없다면 생성)
        if : steps.check-docker.outputs.docker_exists == 'false'
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y \
              ca-certificates \
              curl \
              gnupg \
              lsb-release
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
              | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
              https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" \
              | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo usermod -aG docker $USER
          EOF

      - name: EC2 노드 설치 (없다면 생성)
        if : steps.check-nodejs.outputs.node_exists == 'false'
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} << 'EOF'
            curl -fsSL https://deb,nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt-get install -y node.js
          EOF

      - name: 도커 컴포즈를 통해서 배포
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} <<'EOF'
            cd /home/${{secrets.SERVER_USER}}//backend
            docker compose pull
            docker compose up -d
          EOF
